apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ APP_NAME }}
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ APP_NAME }}
  template:
    metadata:
      labels:
        app: {{ APP_NAME }}
    spec:
      containers:
        - name: {{ APP_NAME }}
          image: registry.edwardnafornita.com/{{ APP_NAME }}:latest
          ports:
            - containerPort: 8080
