name: Template Helm Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, k8s]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login registry.edwardnafornita.com -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t registry.edwardnafornita.com/${{ secrets.APP_NAME }}:latest .
          docker push registry.edwardnafornita.com/${{ secrets.APP_NAME }}:latest

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Install envsubst
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext

      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig
          for file in .github/k8s/*.yaml; do
            envsubst < "$file" > "${file%.yaml}-resolved.yaml"
            kubectl apply -f "${file%.yaml}-resolved.yaml"
          done
        env:
          APP_NAME: ${{ secrets.APP_NAME }}
          IMAGE: ${{ secrets.REGISTRY }}/${{ secrets.APP_NAME }}:latest
