name: Template Helm Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, k8s]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.REGISTRY }}/${{ secrets.APP_NAME }}:latest .
          docker push ${{ secrets.REGISTRY }}/${{ secrets.APP_NAME }}:latest

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy to Kubernetes with Helm
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig
          helm upgrade --install ${{ secrets.APP_NAME }} ./helm-chart \
            --namespace default \
            --set image.repository=${{ secrets.REGISTRY }}/${{ secrets.APP_NAME }} \
            --set image.tag=latest \
            --set appName=${{ secrets.APP_NAME }}
