name: Template Helm Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, k8s]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login registry.edwardnafornita.com -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t registry.edwardnafornita.com/{{ APP_NAME }}:latest .
          docker push registry.edwardnafornita.com/{{ APP_NAME }}:latest

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl apply -f .github/k8s/deployment.yaml
          kubectl apply -f .github/k8s/service.yaml
          kubectl apply -f .github/k8s/virtualservice.yaml
        env:
          APP_NAME: ${{ secrets.APP_NAME }}
          REGISTRY: ${{ secrets.REGISTRY }}
